### PR TITLE
Fix typos in RU

### PR DESCRIPTION
**Pull request by Alex-Sokolov**

### CODE REVIEW

**Comment by pablohpsilva** [comment]
Hello @Alex-Sokolov ! How are you?

Since your PR came after the #28 , would you mind taking a look on everything?

I really appreciate your help! Thank you for your work :D

**Comment by Alex-Sokolov** [comment]
Hi, @pablohpsilva! I'm fine 😄  just resolve conflicts in file

**Comment by pablohpsilva** [comment]
You're awesome @Alex-Sokolov ! Thank you very very much! :D 

You should append your name and info in the end. You've made significant fixes :D

**Comment by Alex-Sokolov** [comment]
But it's only typos) when read I have in mind that some things need to rewrite. Will do this later, and then append name)

**Pull request merged**
