### PR TITLE
Translating to Russian [ru]

### PR DESCRIPTION
**Pull request by shershen08**
I thought it could be really helpful for the community members who have English level that is not yet strong enough to grasp valuable points of the original style guide. So I've created this translation of almost the whole document. 10 out of 14 items are translated for now, I am planning to finalise by next week.
If you think it the link to another language should be added differently or would be good to have other languages in a separate repo or smth, plz let me know.

### CODE REVIEW

**Comment by pablohpsilva** [comment]
Hello @shershen08 ! :D 

Dude, that's amazing!!!! I'll leave the PR here and, once you're done translating I'll accept it.

Thank you for your awesome work! :D

**Comment by shershen08** [comment]
Sure, great, moving on then!

**Comment by pablohpsilva** [comment]
Thank you @shershen08 :D

**Comment by pablohpsilva** [comment]
@shershen08 how are you doing?

Dude, could you please move the "Автор перевода" part to the main README.md file as a special thank you? Something like:

```
# Translation authors
- Russian: Mikhail Kuznetcov [Github](https://github.com/shershen08) (Twitter)[https://twitter.com/legkoletat], [Facebook](https://facebook.com/legkoletat), ...
```

**Comment by shershen08** [comment]
Sure, need to finish one more block and clean up. will do those changes also

**Comment by shershen08** [comment]
should be all gone by now 😉 !
any comments welcome

**Comment by pablohpsilva** [comment]
Thank you! Merged :D

**Pull request merged**
