### PR TITLE
added recommend usage of mixins

### PR DESCRIPTION
**Pull request by ndabAP**

### CODE REVIEW

**Comment by pablohpsilva** [comment]
Hello @ndabAP !!
Dude, thank you for opening this PR. You rock! :D 

Could you please be a little more concise? I think if you remove the first two components (those with the same structure) and show two components using the same mixing it would be better and easier to understand. Something like:

--- 

Mixin
```js
export default = {
  data () {
    return {
      language: 'EN'
    }
  },

  methods: {
    changeLanguage () {
      if (this.language === 'DE') this.$set(this, 'language', 'EN')
      if (this.language === 'EN') this.$set(this, 'language', 'DE')
    }
  }
}
 ```

Component using mixin
```html
<template>
  <ul class="mobile">
    <li @click="changeLanguage">Change language</li>
  </ul>  
</template>

<script>
  import MenuMixin from './MenuMixin'

  export default {
    mixins: [MenuMixin]
  }
</script>
```

What do you think?

**Comment by ndabAP** [comment]
Hey @pablohpsilva, you are welcome :)

With these two components I wanted to show what are potential components that can use mixins. 

You think that these two components (mobile and desktop menu) are too much? Nice idea by the way.

**Comment by pablohpsilva** [comment]
Thank you @ndabAP 
Dude... I think it is. Guidelines should be as simple and straight to the point in my humble opinion.

What do you say? Can you make it even better?

**Comment by ndabAP** [comment]
Hey @pablohpsilva,

yeah, I'm totally with you but I'm not sure what you want from me. Let me sum up what I understand what you want me to do to get this more user friendly:

- Remove two example components (Mobile and Desktop)
- just show a mixin and an example component using it.

If this is alright I'm ready to start :100:

**Comment by pablohpsilva** [comment]
You got it all right :D 
Thank you @ndabAP

**Comment by ndabAP** [comment]
@pablohpsilva, here we go!

**Comment by pablohpsilva** [comment]
Thank you @ndabAP :DDD

**Pull request merged**
