### PR TITLE
Suggestion of improvement - this.refs

### PR DESCRIPTION
**Pull request by Elfayer**
This PR was originated from issue #6 by @kartsims

@pablohpsilva @miljan-aleksic

### CODE REVIEW

**Comment by Elfayer** [comment]
There are twice the title in this commit, sorry.
I can't find a way to commit on the same PR to fix it.

**Comment by pablohpsilva** [comment]
All you have to do is push the changes @Elfayer  :D 
Your PR will change for you. You don't have to create a new PR.

**Comment by Elfayer** [comment]
I'm struggling on the GitHub Desktop app... I'm not sure why it just merged.
Tell me if that's ok.

**Comment by pablohpsilva** [comment]
Thank you @Elfayer ! :D 
PR Accepted.

**Pull request merged**
