### PR TITLE
Name update

### PR DESCRIPTION
**Pull request by wysxhssy**
Already append the name. Thanks for your invite!

### CODE REVIEW

**Comment by pablohpsilva** [comment]
Hello @wysxhlyy :D 
Could you please fix the conflicts and let me know when you're done so I can merge it?

Thank you once again.

**Comment by wysxhlyy** [comment]
Hi Pablo,
        The conflicts have been resolved.


Best regards,
Mario



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=wysxhlyy@gmail.com&idSignature=22>

2017-03-14 11:19 GMT+00:00 Pablo Henrique <notifications@github.com>:

**Comment by wysxhssy** [comment]
hi @pablohpsilva ,conflicts has been resolved

**Comment by pablohpsilva** [comment]
Thank you @wysxhlyy ! :D 

PR accepted.

**Pull request merged**
